[package]
name = "spectre-automation"
version = "0.2.0"
edition = "2024"

[dependencies]
dotenvy = ">= 0.15"
tokio = { version = ">= 1.0", features = ["full"] }
serde = { version = ">= 1.0", features = ["derive"] }
serde_json = ">= 1.0"
plotters = ">= 0.3"
chrono = "0.4" # Добавлено для фиксации даты и времени запусков

# Разрешаем версии выше текущих стабильных
enigo = ">= 0.6"
sysinfo = ">= 0.39"
nvml-wrapper = ">= 0.12"